version: '3'

services:
    spring-boot-docker:
        container_name: spring-boot-docker
        image: spring-boot-docker:adoptopenjdk1
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - /data/spring-boot-docker
        ports:
            - '9800:8080'
        restart: always
